version: '3'

vars:
  GO_VERSION: '1.25.4'
  GOLANGCI_LINT_VERSION: 'v2.6.2'
  GCI_VERSION: 'v0.13.7'
  GOFUMPT_VERSION: 'v0.9.2'
  SWAG_VERSION: 'v1.16.6'
  SQLC_VERSION: 'v1.30.0'
  MOCKERY_VERSION: 'v3.6.1'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  MOCKERY: "{{.BIN_DIR}}/mockery"
  SWAG: '{{.BIN_DIR}}/swag'
  SQLC: '{{.BIN_DIR}}/sqlc'

  COVERAGE_DIR: '{{.ROOT_DIR}}/coverage'
  COVERAGE_FILE: total.out

  MODULES: .

tasks:
  install-formatters:
    desc: "Installs gci and gofumpt formatters in ./bin"
    cmds:
      - |
        [ -f {{.GOFUMPT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo '📦 Installing gofumpt {{.GOFUMPT_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
        }
        [ -f {{.GCI}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo '📦 Installing gci {{.GCI_VERSION}}...'
          GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
        }
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}
  format:
    desc: "Formats the entire project using gofumpt + gci, excluding mocks"
    deps: [ install-formatters ]
    cmds:
      - |
        echo "🎯 Sorting imports with gci ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GCI}} write -s standard -s default -s "prefix(backend)" {} +
      - |
        echo "🧼 Formatting with gofumpt ..."
        find . -type f -name '*.go' ! -path '*/mocks/*' -exec {{.GOFUMPT}} -extra -w {} +

  install-golangci-lint:
    desc: "Installs golangci-lint into the bin directory"
    cmds:
      - |
        [ -f {{.GOLANGCI_LINT}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Installing golangci-lint {{.GOLANGCI_LINT_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
        }
    status:
      - test -x {{.GOLANGCI_LINT}}
  lint:
    desc: "Runs golangci-lint for all modules"
    deps: [ install-golangci-lint ]
    cmds:
      - |
        set -e
        ERR=0
        echo "🔍 Linting backend ..."
        {{.GOLANGCI_LINT}} run ./... --config=.golangci.yaml || ERR=1
        exit $ERR

  install-swag:
    desc: "installs swagger"
    cmds:
      - |
        [ -f {{.SWAG}} ] || {
          mkdir -p {{.BIN_DIR}}
          echo "📦 Installing swag {{.SWAG_VERSION}}..."
          GOBIN={{.BIN_DIR}} go install github.com/swaggo/swag/cmd/swag@{{.SWAG_VERSION}}
        }
    status:
      - test -x {{.SWAG}}
  swag:
    desc: "Generates swagger based on go-code"
    deps: [ install-swag ]
    cmds:
      - |
        {{.SWAG}} init -g cmd/main.go

  mockery:install:
    desc: "Install mockery in ./bin"
    cmds:
      - |
        [ -f {{.MOCKERY}} ] || {
          echo '📦 Installing mockery...'
          GOBIN={{.BIN_DIR}} go install github.com/vektra/mockery/v3@{{.MOCKERY_VERSION}}
        }
    status:
      - test -x {{.MOCKERY}}

  mockery:gen:
    desc: "Generates interface mocks via mockery"
    deps: [ mockery:install ]
    cmds:
      - |
        echo '🧪 Generating mocks...'
        {{.MOCKERY}}

  test:
    desc: "Runs unit tests"
    cmds:
      - |
        ERR=0
        go test -v ./... || ERR=1
        exit $ERR

  test-coverage:
    desc: "Tests with business logic coverage (service/repository)"
    cmds:
      - |
        echo "🧪 Запускаем расчёт покрытия..."
        rm -rf {{.COVERAGE_DIR}}
        mkdir -p {{.COVERAGE_DIR}}
        
        ERR=0
        for mod in {{.MODULES}}; do
          echo "📦 Обрабатываем модуль: $mod"
        
          TARGET_PKGS=$(go list ./$mod/... \
            | grep -E '/(internal/(service|repository))' \
            | grep -vE '/(mocks|testdata|pkg|api|proto|pb|cmd)' \
            | paste -sd "," -)
        
          if [ -z "$TARGET_PKGS" ]; then
            echo "⚠️  Нет подходящих пакетов в $mod"
            continue
          fi
        
          go test -coverpkg="$TARGET_PKGS" \
            -coverprofile={{.COVERAGE_DIR}}/$mod.out \
            -covermode=atomic \
            $(echo "$TARGET_PKGS" | tr "," " ") || ERR=1
        done
        
        if [ $ERR -ne 0 ]; then
          echo "❌ Ошибки во время тестов"
          exit $ERR
        fi
        
        echo
        echo "📊 Покрытие по каждому модулю:"
        for mod in {{.MODULES}}; do
          OUTFILE="{{.COVERAGE_DIR}}/$mod.out"
          if [ -f "$OUTFILE" ]; then
            printf " • %s: " "$mod"
            go tool cover -func="$OUTFILE" | tail -n1
          fi
        done
        
        echo
        echo "📦 Склеиваем все покрытия..."
        {
          echo "mode: atomic"
          find {{.COVERAGE_DIR}} -type f -name '*.out' ! -name '{{.COVERAGE_FILE}}' \
            -exec grep -h -v "^mode:" {} +
        } > {{.COVERAGE_DIR}}/{{.COVERAGE_FILE}}
        
        echo
        echo "🧾 Общее покрытие по всем модулям:"
        go tool cover -func={{.COVERAGE_DIR}}/{{.COVERAGE_FILE}} | tail -n1
  

  dcu:
    cmds:
      - docker compose -f dev-compose.yml up -d
  dcd:
    cmds:
      - docker compose -f dev-compose.yml down
